[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rare_dif"
authors = [
    {name = "Filip Rehburg", email="filip.rehburg@charite.de"},
    {name = "Adam Graefe", email="adam.graefe@charite.de"},
     ]
description = "Rare Disease Interoperability Framework enabling HL7 FHIR and the GA4GH Phenopacket Schema"
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "Rare Disease",
    "Interoperability",
    "FHIR",
    "Phenopacket Schema",
    "REDCap"
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Rare Diseases"
]
dependencies = [
    "numpy",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest>=7.0.0,<8.0.0"]
docs = ["sphinx>=7.0.0", "sphinx-rtd-theme>=1.3.0", "sphinx-copybutton>=0.5.0"]

[project.urls]
homepage = "https://github.com/BIH-CEI/RareDIF"
repository = "https://github.com/BIH-CEI/RareDIF.git"
documentation = "https://BIH-CEI.github.io/RareDIF/stable"
bugtracker = "https://github.com/BIH-CEI/RareDIF/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = { attr = "rare_dif.__version__" }

# The following would provide a command line executable called `sample`
# which executes the function `main` from this package when invoked.
[project.scripts]  # Optional
sample = "sample:main"
